```ruby
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class demo1 {

	
	public static void main(String[] args) {

	}
	
	
	
	
public static void read(){
	FileInputStream file1= null;
	
	try{

		
		File file=new File("D:\\abc.txt");
		file1= new FileInputStream(file);
		int length=0;
		 byte [] a=new byte[1024];
		while((length=file1.read(a))!=-1){
			
			System.out.println(new String(a,0,length));
			
			
		}
}catch(IOException e){
	
	throw  new RuntimeException(e);
	//组织后面的代码执行，并且通知调用者这里出问题
	
//但是return 不能提示信息。
	//System.exit(0);退出虚拟机更加不方便
	
	//所以用throw e;抛出异常，后面的代码就不会执行了,要声明异常，并且调用者要进行处理
	
	/*可以抛出 runtimeException() 运行时异常不用声明,可以包装一层，然后抛出，让调用者使用变得更加灵活。
	好似黄金里面包装了一个炸弹。方法不用声明，调用者可以处理也可以不处理*/
	
	
	//System.exit(0);//退出虚拟机
	
	
	}finally {
		//空管道不要关
		if (file1!=null){
		try{file1.close();}
		catch(IOException e){
			throw new RuntimeException(e);
			
		}
		}
	}
	
	
	
	
}

}
